name: Publish

on:
  push:
    branches: [draft]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: repo-sync/pull-request
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 # v2.12.1
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_allow_empty: false
          pr_label: auto-pr
          pr_title: Publish
          source_branch: ${{ github.ref }}
