name: Publish

on:
  push:
    branches: [draft]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: repo-sync/pull-request
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 # v2.12.1
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_allow_empty: false
          pr_label: auto-pr
          pr_title: Publish
          source_branch: ${{ github.ref }}
