name: Publish

on:
  push:
    branches: [draft]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: repo-sync/pull-request
        uses: repo-sync/pull-request@65785d95a5a466e46a9d0708933a3bd51bbf9dde # tag=v2.6.2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_allow_empty: false
          pr_label: auto-pr
          pr_title: Publish
          source_branch: ${{ github.ref }}
