name: textlint

on:
  push:
    branches:
      - dev
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout@v2.3.4
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: actions/setup-node@v2.1.4
        uses: actions/setup-node@c46424eee26de4078d34105d3de3cc4992202b1e
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Run textlint
        run: |
          npx textlint --fix *.md

      - name: peter-evans/create-pull-request@v3.8.2
        uses: peter-evans/create-pull-request@6bb739433928fbc2bdc635d41105e124d0dce021
        with:
          branch-suffix: short-commit-hash
          branch: typo/auto-fix
          delete-branch: true
          labels: auto-pr
          title: Fix typo
