name: textlint

on:
  push:
    branches:
      - dev
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: actions/setup-node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2.4.1
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run textlint
        run: |
          npx textlint --fix *.md

      - name: peter-evans/create-pull-request
        uses: peter-evans/create-pull-request@67df31e08a133c6a77008b89689677067fef169e # renovate: tag=v3.11.0
        with:
          branch-suffix: short-commit-hash
          branch: typo/auto-fix
          delete-branch: true
          labels: auto-pr
          title: Fix typo
