name: textlint

on:
  push:
    branches:
      - dev
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout@v2.3.4
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d

      - name: actions/setup-node@v2.1.4
        uses: actions/setup-node@c46424eee26de4078d34105d3de3cc4992202b1e
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Run textlint
        run: |
          npx textlint --fix *.md

      - name: peter-evans/create-pull-request@v3.8.2
        uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8
        with:
          branch-suffix: short-commit-hash
          branch: typo/auto-fix
          delete-branch: true
          labels: auto-pr
          title: Fix typo
