name: textlint

on:
  push:
    branches:
      - dev
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout@v2.3.4
        uses: actions/checkout@fd47087372161c6f2a7b96d2ef87e944d89023ed

      - name: actions/setup-node@v2.1.4
        uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Run textlint
        run: |
          npx textlint --fix *.md

      - name: peter-evans/create-pull-request@v3.8.2
        uses: peter-evans/create-pull-request@95767e7d51a7ebe6b4820b6ee9432ed9e747ef89
        with:
          branch-suffix: short-commit-hash
          branch: typo/auto-fix
          delete-branch: true
          labels: auto-pr
          title: Fix typo
