name: textlint

on:
  push:
    branches:
      - dev
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout@v2.3.4
        uses: actions/checkout@afe4af09a72596f47d806ee5f8b2674ec07fdc73

      - name: actions/setup-node@v2.1.4
        uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Run textlint
        run: |
          npx textlint --fix *.md

      - name: peter-evans/create-pull-request@v3.8.2
        uses: peter-evans/create-pull-request@3c3d696d5b8aa2eb0e70f76c251e4b149122acf1
        with:
          branch-suffix: short-commit-hash
          branch: typo/auto-fix
          delete-branch: true
          labels: auto-pr
          title: Fix typo
