name: textlint

on:
  push:
    branches:
      - dev
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout@v2.3.4
        uses: actions/checkout@afe4af09a72596f47d806ee5f8b2674ec07fdc73

      - name: actions/setup-node@v2.1.4
        uses: actions/setup-node@aa759c6c94d3800c55b8601f21ba4b2371704cb7
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Run textlint
        run: |
          npx textlint --fix *.md

      - name: peter-evans/create-pull-request@v3.8.2
        uses: peter-evans/create-pull-request@b90b9c1e2098cfe0e591f2e529cdf554270eacc1
        with:
          branch-suffix: short-commit-hash
          branch: typo/auto-fix
          delete-branch: true
          labels: auto-pr
          title: Fix typo
