name: Update main

on:
  push:
    branches: [draft]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: repo-sync/pull-request
        uses: repo-sync/pull-request@65785d95a5a466e46a9d0708933a3bd51bbf9dde # tag=v2.6.2
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_allow_empty: false
          pr_label: auto-pr
          pr_title: Update main
          source_branch: ${{ github.ref }}
