name: Update main

on:
  push:
    branches:
      - dev

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout@v2.3.4
        uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7

      - name: repo-sync/pull-request@v2.5
        uses: repo-sync/pull-request@5ba2c80b97c87b9174c1548141b7acd80f6376e1
        with:
          source_branch: ${{ github.ref }}
          destination_branch: main
          pr_title: Update main
          pr_label: auto-pr
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
