name: Update main

on:
  push:
    branches: [draft]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      - name: repo-sync/pull-request
        uses: repo-sync/pull-request@5ba2c80b97c87b9174c1548141b7acd80f6376e1 # renovate: tag=v2.6.1
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_allow_empty: false
          pr_label: auto-pr
          pr_title: Update main
          source_branch: ${{ github.ref }}
