name: Update main

on:
  push:
    branches:
      - dev

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout@v2.3.4
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d

      - name: repo-sync/pull-request@v2.5
        uses: repo-sync/pull-request@d80b305e358ef8131f270608735c72e2c913f2af
        with:
          source_branch: ${{ github.ref }}
          destination_branch: main
          pr_title: Update main
          pr_label: auto-pr
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
